### ISSUE TITLE
Introspection of INTERFACE results in an error

### ISSUE THREAD

**Issue by sandwichsudo** [potatosalad/graphql-introspection-json-to-sdl#1]
Hi, thanks for open sourcing this, looks very useful. I'm trying to transform the schema downloaded from my graphql api. 
I have an interface in the project:

``` python
class ProductType(graphene.Interface):
     created_at = graphene.DateTime()
     # other fields
```
When I run 

``` 
yarn graphql-introspection-json-to-sdl /Users/user/projects/projectname/src/interfaces/fragmentTypes.json

```
I get the following error:
``` 
Error: Introspection result missing fields: { kind: "INTERFACE", name: "ProductType", possibleTypes: [[Object], [Object]] }
    at buildFieldDefMap (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/utilities/buildClientSchema.js:256:13)
    at fields (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/utilities/buildClientSchema.js:202:16)
    at resolveThunk (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/type/definition.js:383:40)
    at defineFieldMap (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/type/definition.js:567:18)
    at GraphQLInterfaceType.getFields (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/type/definition.js:665:27)
    at typeMapReducer (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/type/schema.js:320:61)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/type/schema.js:145:28)
    at Object.buildClientSchema (/Users/user/projects/projectname/src/interfaces/node_modules/graphql/utilities/buildClientSchema.js:73:10
```

Any advice on what might be causing this issue would be great, many thanks.

**Comment by sandwichsudo** [comment]
This was user error when downloading the schema.
